name: markov
description:
  A simple Markov chain implementation. Generates words and
  punctuation. Tuned for tweets.
version: 0.0.2
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/markov

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
 string_scanner: ^0.1.4+1
 quiver: ^0.21.4

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
